name: Android APK (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Prepare Capacitor (init + deps)
        run: |
          npm i -D @capacitor/cli@latest @capacitor/android@latest
          npm i @capacitor/core@latest
          if [ ! -f capacitor.config.ts ] && [ ! -f capacitor.config.json ]; then
            npx cap init "Speak Build APK" "com.frucht718.speakbuildapk" --web-dir=dist
          fi

      - name: Build web (Vite)
        run: npm run build

      - name: Add Android
        run: |
          npx cap add android || true
          echo "org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC" >> android/gradle.properties

      - name: Put Icon with ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          if [ -f assets/icon.png ]; then
            RES="android/app/src/main/res"
            declare -A SZ=( [mdpi]=48 [hdpi]=72 [xhdpi]=96 [xxhdpi]=144 [xxxhdpi]=192 )
            IM_BIN="convert"; command -v magick >/dev/null 2>&1 && IM_BIN="magick convert"
            for D in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
              mkdir -p "$RES/mipmap-$D"
              $IM_BIN assets/icon.png -resize "${SZ[$D]}x${SZ[$D]}" "$RES/mipmap-$D/ic_launcher.png"
              $IM_BIN assets/icon.png -resize "${SZ[$D]}x${SZ[$D]}" "$RES/mipmap-$D/ic_launcher_round.png"
            done
          else
            echo "WARN: assets/icon.png fehlt – Standard-Launcher bleibt."
          fi

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Sync Android
        run: npx cap sync android

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew :app:assembleDebug

      - name: List Gradle outputs
        run: |
          echo "=== outputs tree ==="
          ls -R android/app/build/outputs || true

      - name: Collect APKs
        shell: bash
        run: |
          set -Eeuo pipefail
          shopt -s globstar nullglob
          mkdir -p apk_out
          files=(android/app/build/outputs/**/*.apk android/app/build/outputs/**/*.aab)
          if [ ${#files[@]} -eq 0 ]; then
            echo "Keine APK/AAB gefunden. Baum:"
            find android/app/build -maxdepth 5 -type f | sed "s#^#  #"
            exit 1
          fi
          printf "Kopiere %d Datei(en):\n" "${#files[@]}"
          cp -v "${files[@]}" apk_out/
          ls -lh apk_out

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: apk_out/*
          if-no-files-found: error
          retention-days: 7
