name: Android APK (Capacitor)
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      - name: Upload web dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist
          if-no-files-found: error
          retention-days: 3

  android-debug:
    runs-on: ubuntu-latest
    needs: web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Prepare Capacitor (init + deps)
        run: |
          npm i -D @capacitor/cli@latest @capacitor/android@latest
          npm i @capacitor/core@latest
          if [ ! -f capacitor.config.ts ] && [ ! -f capacitor.config.json ]; then
            npx cap init "Speak Build APK" "com.frucht718.speakbuildapk" --web-dir=dist
          fi

      - name: Build web (Vite)
        run: npm run build

      - name: Add Android platform
        run: |
          if [ ! -d android ]; then
            npx cap add android
          fi
          chmod +x android/gradlew || true
          echo "=== android root ==="; ls -la android || true
          test -f android/gradlew || { echo "::error::gradlew fehlt"; exit 1; }

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses || true

      - name: Capacitor sync
        run: npx cap sync android

      - name: Build Debug APK
        working-directory: android
        run: |
          set -euxo pipefail
          ./gradlew --version
          ./gradlew :app:assembleDebug --no-daemon --stacktrace --warning-mode all

      - name: List APKs
        run: ls -R android/app/build/outputs/apk || true

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
          retention-days: 7
