name: Android APK (Capacitor)
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sanity check
        run: |
          echo "workflow ok"
