name: Android APK (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Prepare Capacitor (ohne @capacitor/assets)
        run: |
          npm i -D @capacitor/cli
          npm i @capacitor/core
          if [ ! -f capacitor.config.ts ] && [ ! -f capacitor.config.json ]; then
            npx cap init "Speak Build APK" "com.frucht718.speakbuildapk" --web-dir=dist
          fi

      - name: Build web (Vite)
        run: npm run build

      - name: Add Android + Put Icon (ImageMagick, no sharp)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          npx cap add android || true
          npx cap sync android
          if [ -f assets/icon.png ]; then
            RES="android/app/src/main/res"
            declare -A SZ=( [mdpi]=48 [hdpi]=72 [xhdpi]=96 [xxhdpi]=144 [xxxhdpi]=192 )
            for D in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
              mkdir -p "$RES/mipmap-$D"
              convert assets/icon.png -resize "${SZ[$D]}x${SZ[$D]}" "$RES/mipmap-$D/ic_launcher.png"
              convert assets/icon.png -resize "${SZ[$D]}x${SZ[$D]}" "$RES/mipmap-$D/ic_launcher_round.png"
            done
          fi
          # etwas RAM für Gradle
          echo "org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC" | tee -a android/gradle.properties >/dev/null

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Build Release APK
        working-directory: android
        run: ./gradlew :app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android/app/build/outputs/apk/release/*.apk
